export const defaultImages = [
  {
    id: "cwJ941Yw8gw",
    slug: "a-mountain-range-covered-in-snow-under-a-cloudy-sky-cwJ941Yw8gw",
    alternative_slugs: {
      en: "a-mountain-range-covered-in-snow-under-a-cloudy-sky-cwJ941Yw8gw",
      es: "una-cadena-montanosa-cubierta-de-nieve-bajo-un-cielo-nublado-cwJ941Yw8gw",
      ja: "曇り空の下で雪に覆われた山脈-cwJ941Yw8gw",
      fr: "une-chaine-de-montagnes-couverte-de-neige-sous-un-ciel-nuageux-cwJ941Yw8gw",
      it: "una-catena-montuosa-coperta-di-neve-sotto-un-cielo-nuvoloso-cwJ941Yw8gw",
      ko: "흐린-하늘-아래-눈으로-덮인-산맥-cwJ941Yw8gw",
      de: "eine-schneebedeckte-bergkette-unter-einem-bewolkten-himmel-cwJ941Yw8gw",
      pt: "uma-cordilheira-coberta-de-neve-sob-um-ceu-nublado-cwJ941Yw8gw",
    },
    created_at: "2021-10-04T00:23:04Z",
    updated_at: "2024-08-26T20:48:57Z",
    promoted_at: "2021-10-04T13:08:01Z",
    width: 6240,
    height: 4160,
    color: "#262626",
    blur_hash: "LGATi@IT9FtR~qRjIUbIxCt7ogM|",
    description: null,
    alt_description: "a mountain range covered in snow under a cloudy sky",
    breadcrumbs: [
      {
        slug: "images",
        title: "1,000,000+ Free Images",
        index: 0,
        type: "landing_page",
      },
      {
        slug: "nature",
        title: "Nature Images",
        index: 1,
        type: "landing_page",
      },
      {
        slug: "sunset",
        title: "Sunset Images & Pictures",
        index: 2,
        type: "landing_page",
      },
    ],
    urls: {
      raw: "https://images.unsplash.com/photo-1633306946374-d64e9fca8734?ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1633306946374-d64e9fca8734?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1633306946374-d64e9fca8734?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1633306946374-d64e9fca8734?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1633306946374-d64e9fca8734?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1633306946374-d64e9fca8734",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-mountain-range-covered-in-snow-under-a-cloudy-sky-cwJ941Yw8gw",
      html: "https://unsplash.com/photos/a-mountain-range-covered-in-snow-under-a-cloudy-sky-cwJ941Yw8gw",
      download:
        "https://unsplash.com/photos/cwJ941Yw8gw/download?ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8",
      download_location:
        "https://api.unsplash.com/photos/cwJ941Yw8gw/download?ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8",
    },
    likes: 123,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      nature: {
        status: "rejected",
      },
    },
    asset_type: "photo",
    user: {
      id: "NHGv49zP3WQ",
      updated_at: "2024-10-02T00:18:28Z",
      username: "kalaniparker",
      name: "Kellen Riggin",
      first_name: "Kellen",
      last_name: "Riggin",
      twitter_username: "Kalaniparkr",
      portfolio_url: null,
      bio: "Photography with a vibe. Chasing my dream one picture at a time. Based in San Francisco, CA.",
      location: "California",
      links: {
        self: "https://api.unsplash.com/users/kalaniparker",
        html: "https://unsplash.com/@kalaniparker",
        photos: "https://api.unsplash.com/users/kalaniparker/photos",
        likes: "https://api.unsplash.com/users/kalaniparker/likes",
        portfolio: "https://api.unsplash.com/users/kalaniparker/portfolio",
        following: "https://api.unsplash.com/users/kalaniparker/following",
        followers: "https://api.unsplash.com/users/kalaniparker/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1721325096807-b4dcc18d48bbimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1721325096807-b4dcc18d48bbimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1721325096807-b4dcc18d48bbimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "kalaniparker",
      total_collections: 0,
      total_likes: 360,
      total_photos: 955,
      total_promoted_photos: 347,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: "kalaniparker",
        portfolio_url: null,
        twitter_username: "Kalaniparkr",
        paypal_email: null,
      },
    },
    exif: {
      make: "FUJIFILM",
      model: "X-T3",
      name: "FUJIFILM, X-T3",
      exposure_time: "1/250",
      aperture: "8",
      focal_length: "55.0",
      iso: 160,
    },
    location: {
      name: "Yosemite Valley, CA, USA",
      city: "Yosemite Valley",
      country: "United States",
      position: {
        latitude: 37.74557,
        longitude: -119.593604,
      },
    },
    views: 7247708,
    downloads: 21259,
  },
  {
    id: "GNe20vFefq4",
    slug: "white-and-red-lighthouse-on-sea-during-sunset-GNe20vFefq4",
    alternative_slugs: {
      en: "white-and-red-lighthouse-on-sea-during-sunset-GNe20vFefq4",
      es: "faro-blanco-y-rojo-en-el-mar-durante-la-puesta-de-sol-GNe20vFefq4",
      ja: "日没時の海に浮かぶ白と赤の灯台-GNe20vFefq4",
      fr: "phare-blanc-et-rouge-sur-la-mer-au-coucher-du-soleil-GNe20vFefq4",
      it: "faro-bianco-e-rosso-sul-mare-durante-il-tramonto-GNe20vFefq4",
      ko: "일몰-동안-바다에-흰색과-빨간색-등대-GNe20vFefq4",
      de: "weisser-und-roter-leuchtturm-auf-see-bei-sonnenuntergang-GNe20vFefq4",
      pt: "farol-branco-e-vermelho-no-mar-durante-o-por-do-sol-GNe20vFefq4",
    },
    created_at: "2020-03-18T16:54:49Z",
    updated_at: "2024-08-26T20:30:50Z",
    promoted_at: "2020-03-19T13:27:06Z",
    width: 2000,
    height: 3000,
    color: "#404040",
    blur_hash: "LB7-NTIUxYWBo}j@Rjay0K%2Ipt7",
    description: "instagram.com/vadimsadovski",
    alt_description: "white and red lighthouse on sea during sunset",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1584550411759-383a9893ec19?ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1584550411759-383a9893ec19?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1584550411759-383a9893ec19?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1584550411759-383a9893ec19?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1584550411759-383a9893ec19?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1584550411759-383a9893ec19",
    },
    links: {
      self: "https://api.unsplash.com/photos/white-and-red-lighthouse-on-sea-during-sunset-GNe20vFefq4",
      html: "https://unsplash.com/photos/white-and-red-lighthouse-on-sea-during-sunset-GNe20vFefq4",
      download:
        "https://unsplash.com/photos/GNe20vFefq4/download?ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8",
      download_location:
        "https://api.unsplash.com/photos/GNe20vFefq4/download?ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8",
    },
    likes: 220,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "YZ06DPhNr4M",
      updated_at: "2024-10-01T19:27:03Z",
      username: "vadimsadovski",
      name: "Vadim Sadovski",
      first_name: "Vadim",
      last_name: "Sadovski",
      twitter_username: null,
      portfolio_url: "https://linktr.ee/vadimsadovski",
      bio: null,
      location: null,
      links: {
        self: "https://api.unsplash.com/users/vadimsadovski",
        html: "https://unsplash.com/@vadimsadovski",
        photos: "https://api.unsplash.com/users/vadimsadovski/photos",
        likes: "https://api.unsplash.com/users/vadimsadovski/likes",
        portfolio: "https://api.unsplash.com/users/vadimsadovski/portfolio",
        following: "https://api.unsplash.com/users/vadimsadovski/following",
        followers: "https://api.unsplash.com/users/vadimsadovski/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1567842240492-5065803f8cf7image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1567842240492-5065803f8cf7image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1567842240492-5065803f8cf7image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "vadimsadovski",
      total_collections: 0,
      total_likes: 82,
      total_photos: 269,
      total_promoted_photos: 248,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: "vadimsadovski",
        portfolio_url: "https://linktr.ee/vadimsadovski",
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: "NIKON CORPORATION",
      model: "NIKON D850",
      name: "NIKON CORPORATION, NIKON D850",
      exposure_time: "1/8000",
      aperture: "1.4",
      focal_length: "35.0",
      iso: 140,
    },
    location: {
      name: "Henningsvær, Норвегия",
      city: "Хеннингсвер",
      country: "Норвегия",
      position: {
        latitude: 68.154187,
        longitude: 14.207254,
      },
    },
    views: 7769629,
    downloads: 9211,
  },
  {
    id: "F6ZpaTx5e3M",
    slug: "yellow-smoke-coming-out-from-jack-o-lantern-F6ZpaTx5e3M",
    alternative_slugs: {
      en: "yellow-smoke-coming-out-from-jack-o-lantern-F6ZpaTx5e3M",
      es: "humo-amarillo-que-sale-de-jack-o-lantern-F6ZpaTx5e3M",
      ja: "ジャックオランタンから出てくる黄色い煙-F6ZpaTx5e3M",
      fr: "fumee-jaune-sortant-de-jack-o-lantern-F6ZpaTx5e3M",
      it: "fumo-giallo-che-esce-da-jack-o-lantern-F6ZpaTx5e3M",
      ko: "jack-o-lantern에서-나오는-노란-연기-F6ZpaTx5e3M",
      de: "gelber-rauch-kommt-aus-jack-o-lantern-F6ZpaTx5e3M",
      pt: "fumaca-amarela-saindo-de-jack-o-lantern-F6ZpaTx5e3M",
    },
    created_at: "2018-10-29T20:19:51Z",
    updated_at: "2024-10-02T10:24:29Z",
    promoted_at: "2018-10-31T14:41:52Z",
    width: 2970,
    height: 3712,
    color: "#262626",
    blur_hash: "LB9?zCD.KMtM9wbYn%jb0R-,#nRU",
    description: null,
    alt_description: "yellow smoke coming out from Jack-O-Lantern",
    breadcrumbs: [
      {
        slug: "images",
        title: "1,000,000+ Free Images",
        index: 0,
        type: "landing_page",
      },
      {
        slug: "things",
        title: "Things Images",
        index: 1,
        type: "landing_page",
      },
      {
        slug: "skull",
        title: "Skull Images & Pictures",
        index: 2,
        type: "landing_page",
      },
    ],
    urls: {
      raw: "https://images.unsplash.com/photo-1540844251825-f369876ae9a5?ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1540844251825-f369876ae9a5?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1540844251825-f369876ae9a5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1540844251825-f369876ae9a5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1540844251825-f369876ae9a5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1540844251825-f369876ae9a5",
    },
    links: {
      self: "https://api.unsplash.com/photos/yellow-smoke-coming-out-from-jack-o-lantern-F6ZpaTx5e3M",
      html: "https://unsplash.com/photos/yellow-smoke-coming-out-from-jack-o-lantern-F6ZpaTx5e3M",
      download:
        "https://unsplash.com/photos/F6ZpaTx5e3M/download?ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8",
      download_location:
        "https://api.unsplash.com/photos/F6ZpaTx5e3M/download?ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8",
    },
    likes: 454,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "OYFefN8EKy0",
      updated_at: "2024-09-30T23:17:39Z",
      username: "danny_lincoln",
      name: "Daniel Lincoln",
      first_name: "Daniel",
      last_name: "Lincoln",
      twitter_username: "Lincoln_Danny",
      portfolio_url: "https://www.youtube.com/dannylincoln",
      bio: "Coffee and Create.\r\nFollow my IG for more content. @danny.lincoln",
      location: "Los Angeles, CA",
      links: {
        self: "https://api.unsplash.com/users/danny_lincoln",
        html: "https://unsplash.com/@danny_lincoln",
        photos: "https://api.unsplash.com/users/danny_lincoln/photos",
        likes: "https://api.unsplash.com/users/danny_lincoln/likes",
        portfolio: "https://api.unsplash.com/users/danny_lincoln/portfolio",
        following: "https://api.unsplash.com/users/danny_lincoln/following",
        followers: "https://api.unsplash.com/users/danny_lincoln/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-fb-1522857800-5763b6c50a98.jpg?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-fb-1522857800-5763b6c50a98.jpg?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-fb-1522857800-5763b6c50a98.jpg?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "danny.lincoln",
      total_collections: 1,
      total_likes: 345,
      total_photos: 511,
      total_promoted_photos: 159,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: "danny.lincoln",
        portfolio_url: "https://www.youtube.com/dannylincoln",
        twitter_username: "Lincoln_Danny",
        paypal_email: null,
      },
    },
    exif: {
      make: "Canon",
      model: "Canon EOS 80D",
      name: "Canon, EOS 80D",
      exposure_time: "1/1000",
      aperture: "2.8",
      focal_length: "24.0",
      iso: 100,
    },
    location: {
      name: null,
      city: null,
      country: null,
      position: {
        latitude: null,
        longitude: null,
      },
    },
    views: 3779068,
    downloads: 13310,
  },
  {
    id: "z0LekqawELA",
    slug: "gray-textile-on-brown-wicker-basket-with-book-on-top-z0LekqawELA",
    alternative_slugs: {
      en: "gray-textile-on-brown-wicker-basket-with-book-on-top-z0LekqawELA",
      es: "textil-gris-sobre-cesta-de-mimbre-marron-con-libro-en-la-parte-superior-z0LekqawELA",
      ja: "茶色の籐のバスケットに灰色のテキスタイル上に本-z0LekqawELA",
      fr: "textile-gris-sur-panier-en-osier-marron-avec-livre-sur-le-dessus-z0LekqawELA",
      it: "tessuto-grigio-su-cesto-di-vimini-marrone-con-libro-in-cima-z0LekqawELA",
      ko: "갈색-고리-버들-세공-바구니에-회색-직물-위에-책이-있습니다-z0LekqawELA",
      de: "graues-textil-auf-braunem-weidenkorb-mit-buch-oben-drauf-z0LekqawELA",
      pt: "tecido-cinza-na-cesta-de-vime-marrom-com-livro-na-parte-superior-z0LekqawELA",
    },
    created_at: "2017-09-27T20:53:39Z",
    updated_at: "2024-10-02T09:05:26Z",
    promoted_at: "2017-09-28T11:17:26Z",
    width: 6720,
    height: 4480,
    color: "#262626",
    blur_hash: "L66H+JoL00IoE1WB%Mt79FWB.8xa",
    description:
      "My mama’s apple garden is one of my favorite places to get away and read a good book.",
    alt_description: "gray textile on brown wicker basket with book on top",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1506545526820-9fd2eb7865c5?ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1506545526820-9fd2eb7865c5?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1506545526820-9fd2eb7865c5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1506545526820-9fd2eb7865c5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1506545526820-9fd2eb7865c5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1506545526820-9fd2eb7865c5",
    },
    links: {
      self: "https://api.unsplash.com/photos/gray-textile-on-brown-wicker-basket-with-book-on-top-z0LekqawELA",
      html: "https://unsplash.com/photos/gray-textile-on-brown-wicker-basket-with-book-on-top-z0LekqawELA",
      download:
        "https://unsplash.com/photos/z0LekqawELA/download?ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8",
      download_location:
        "https://api.unsplash.com/photos/z0LekqawELA/download?ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8",
    },
    likes: 657,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "mkTP6oKsF2k",
      updated_at: "2024-09-26T17:58:54Z",
      username: "lianamikah",
      name: "Liana Mikah",
      first_name: "Liana",
      last_name: "Mikah",
      twitter_username: "lianamikah",
      portfolio_url: "http://lianamikah.com",
      bio: "designer, photographer & social media curator in portland, OR",
      location: "portland, or",
      links: {
        self: "https://api.unsplash.com/users/lianamikah",
        html: "https://unsplash.com/@lianamikah",
        photos: "https://api.unsplash.com/users/lianamikah/photos",
        likes: "https://api.unsplash.com/users/lianamikah/likes",
        portfolio: "https://api.unsplash.com/users/lianamikah/portfolio",
        following: "https://api.unsplash.com/users/lianamikah/following",
        followers: "https://api.unsplash.com/users/lianamikah/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1502565518071-0757cd74b5a5?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1502565518071-0757cd74b5a5?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1502565518071-0757cd74b5a5?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "lianamikah",
      total_collections: 18,
      total_likes: 1264,
      total_photos: 134,
      total_promoted_photos: 60,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: "lianamikah",
        portfolio_url: "http://lianamikah.com",
        twitter_username: "lianamikah",
        paypal_email: null,
      },
    },
    exif: {
      make: "Canon",
      model: "Canon EOS 5D Mark IV",
      name: "Canon, EOS 5D Mark IV",
      exposure_time: "1/500",
      aperture: "2.2",
      focal_length: "50.0",
      iso: 125,
    },
    location: {
      name: null,
      city: null,
      country: null,
      position: {
        latitude: null,
        longitude: null,
      },
    },
    views: 7737198,
    downloads: 12984,
  },
  {
    id: "fHOCjVoVj6g",
    slug: "brown-abstract-painting-fHOCjVoVj6g",
    alternative_slugs: {
      en: "brown-abstract-painting-fHOCjVoVj6g",
      es: "brown-abstract-painting-fHOCjVoVj6g",
      ja: "brown-abstract-painting-fHOCjVoVj6g",
      fr: "brown-abstract-painting-fHOCjVoVj6g",
      it: "brown-abstract-painting-fHOCjVoVj6g",
      ko: "brown-abstract-painting-fHOCjVoVj6g",
      de: "brown-abstract-painting-fHOCjVoVj6g",
      pt: "brown-abstract-painting-fHOCjVoVj6g",
    },
    created_at: "2018-02-02T15:06:16Z",
    updated_at: "2024-10-01T21:07:11Z",
    promoted_at: "2018-02-02T19:06:55Z",
    width: 4961,
    height: 3259,
    color: "#404040",
    blur_hash: "LCC6PtR-Ipfk~UEMNHay%1NHs.oe",
    description:
      "We mostly do technical aerial photography for terrain analysis and animal studies. Occasionally a scene presents itself, like this buffalo herd at sunrise and a few shots out the aircraft passengers window cannot be resisted.",
    alt_description: "brown abstract painting",
    breadcrumbs: [
      {
        slug: "images",
        title: "1,000,000+ Free Images",
        index: 0,
        type: "landing_page",
      },
      {
        slug: "feelings",
        title: "Feelings Images",
        index: 1,
        type: "landing_page",
      },
      {
        slug: "cool",
        title: "Cool Images & Photos",
        index: 2,
        type: "landing_page",
      },
    ],
    urls: {
      raw: "https://images.unsplash.com/photo-1517583660619-ce9ab709528f?ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1517583660619-ce9ab709528f?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1517583660619-ce9ab709528f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1517583660619-ce9ab709528f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1517583660619-ce9ab709528f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1517583660619-ce9ab709528f",
    },
    links: {
      self: "https://api.unsplash.com/photos/brown-abstract-painting-fHOCjVoVj6g",
      html: "https://unsplash.com/photos/brown-abstract-painting-fHOCjVoVj6g",
      download:
        "https://unsplash.com/photos/fHOCjVoVj6g/download?ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8",
      download_location:
        "https://api.unsplash.com/photos/fHOCjVoVj6g/download?ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8",
    },
    likes: 342,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      animals: {
        status: "approved",
        approved_on: "2020-04-06T14:20:16Z",
      },
    },
    asset_type: "photo",
    user: {
      id: "bl2BUrVihG0",
      updated_at: "2024-05-21T20:26:47Z",
      username: "wynand_uys",
      name: "Wynand Uys",
      first_name: "Wynand",
      last_name: "Uys",
      twitter_username: "WynandUys",
      portfolio_url: null,
      bio: "Aerial (not drone) -photography of a technical nature. Photogrammetry, wildlife surveys, air support to wildlife protection groups.",
      location: "Hoedspruit, Limpopo, South Africa",
      links: {
        self: "https://api.unsplash.com/users/wynand_uys",
        html: "https://unsplash.com/@wynand_uys",
        photos: "https://api.unsplash.com/users/wynand_uys/photos",
        likes: "https://api.unsplash.com/users/wynand_uys/likes",
        portfolio: "https://api.unsplash.com/users/wynand_uys/portfolio",
        following: "https://api.unsplash.com/users/wynand_uys/following",
        followers: "https://api.unsplash.com/users/wynand_uys/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-fb-1517583010-df1c3add006b.jpg?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-fb-1517583010-df1c3add006b.jpg?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-fb-1517583010-df1c3add006b.jpg?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: null,
      total_collections: 0,
      total_likes: 29,
      total_photos: 25,
      total_promoted_photos: 11,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: false,
      for_hire: false,
      social: {
        instagram_username: null,
        portfolio_url: null,
        twitter_username: "WynandUys",
        paypal_email: null,
      },
    },
    exif: {
      make: "Canon",
      model: "Canon EOS 6D",
      name: "Canon, EOS 6D",
      exposure_time: "1/4000",
      aperture: "5.6",
      focal_length: "300.0",
      iso: 1000,
    },
    location: {
      name: "Timbavati Game Reserve, Hoedspruit, South Africa",
      city: "Hoedspruit",
      country: "South Africa",
      position: {
        latitude: -24.33877333,
        longitude: 31.25619667,
      },
    },
    views: 7279810,
    downloads: 12008,
  },
  {
    id: "1S0YHBS77DI",
    slug: "a-boat-is-docked-in-the-water-in-front-of-a-snowy-mountain-1S0YHBS77DI",
    alternative_slugs: {
      en: "a-boat-is-docked-in-the-water-in-front-of-a-snowy-mountain-1S0YHBS77DI",
      es: "un-barco-esta-atracado-en-el-agua-frente-a-una-montana-nevada-1S0YHBS77DI",
      ja: "雪山の手前の水面にボートが停泊している-1S0YHBS77DI",
      fr: "un-bateau-est-amarre-dans-leau-devant-une-montagne-enneigee-1S0YHBS77DI",
      it: "una-barca-e-ormeggiata-nellacqua-di-fronte-a-una-montagna-innevata-1S0YHBS77DI",
      ko: "설산-앞-물에-배가-정박해-있다-1S0YHBS77DI",
      de: "ein-boot-liegt-im-wasser-vor-einem-verschneiten-berg-1S0YHBS77DI",
      pt: "um-barco-esta-ancorado-na-agua-em-frente-a-uma-montanha-nevada-1S0YHBS77DI",
    },
    created_at: "2024-03-18T12:16:05Z",
    updated_at: "2024-08-26T21:09:19Z",
    promoted_at: "2024-03-25T06:36:40Z",
    width: 4000,
    height: 6000,
    color: "#f3d9f3",
    blur_hash: "LyLzzQR%WEfj~WofjZj[-ooLaxfR",
    description: null,
    alt_description:
      "a boat is docked in the water in front of a snowy mountain",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1710762634511-437ff5268243?ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1710762634511-437ff5268243?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1710762634511-437ff5268243?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1710762634511-437ff5268243?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1710762634511-437ff5268243?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1710762634511-437ff5268243",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-boat-is-docked-in-the-water-in-front-of-a-snowy-mountain-1S0YHBS77DI",
      html: "https://unsplash.com/photos/a-boat-is-docked-in-the-water-in-front-of-a-snowy-mountain-1S0YHBS77DI",
      download:
        "https://unsplash.com/photos/1S0YHBS77DI/download?ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8",
      download_location:
        "https://api.unsplash.com/photos/1S0YHBS77DI/download?ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8",
    },
    likes: 136,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      wallpapers: {
        status: "approved",
        approved_on: "2024-03-25T16:44:19Z",
      },
      "earth-hour": {
        status: "approved",
        approved_on: "2024-03-22T18:24:38Z",
      },
    },
    asset_type: "photo",
    user: {
      id: "2_KEECgvnKU",
      updated_at: "2024-09-28T05:14:04Z",
      username: "k4media",
      name: "Bingqi Huang",
      first_name: "Bingqi",
      last_name: "Huang",
      twitter_username: null,
      portfolio_url: null,
      bio: null,
      location: "Amsterdam, Netherlands",
      links: {
        self: "https://api.unsplash.com/users/k4media",
        html: "https://unsplash.com/@k4media",
        photos: "https://api.unsplash.com/users/k4media/photos",
        likes: "https://api.unsplash.com/users/k4media/likes",
        portfolio: "https://api.unsplash.com/users/k4media/portfolio",
        following: "https://api.unsplash.com/users/k4media/following",
        followers: "https://api.unsplash.com/users/k4media/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1659518679925-c48fd5e999d8?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1659518679925-c48fd5e999d8?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1659518679925-c48fd5e999d8?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "k4_media",
      total_collections: 0,
      total_likes: 11,
      total_photos: 176,
      total_promoted_photos: 2,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: "k4_media",
        portfolio_url: null,
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: "SONY",
      model: "ILCE-7M3",
      name: "SONY, ILCE-7M3",
      exposure_time: "1/50",
      aperture: "4.0",
      focal_length: "105.0",
      iso: 160,
    },
    location: {
      name: "Lofoten, Norway",
      city: null,
      country: "Norway",
      position: {
        latitude: 68.208607,
        longitude: 13.915737,
      },
    },
    views: 5895448,
    downloads: 103383,
  },
  {
    id: "cs0sK0gzqCU",
    slug: "mountain-near-body-of-water-cs0sK0gzqCU",
    alternative_slugs: {
      en: "mountain-near-body-of-water-cs0sK0gzqCU",
      es: "montana-cerca-del-cuerpo-de-agua-cs0sK0gzqCU",
      ja: "水域近くの山-cs0sK0gzqCU",
      fr: "montagne-pres-dun-plan-deau-cs0sK0gzqCU",
      it: "montagna-vicino-allo-specchio-dacqua-cs0sK0gzqCU",
      ko: "수역-근처의-산-cs0sK0gzqCU",
      de: "berg-in-der-nahe-des-gewassers-cs0sK0gzqCU",
      pt: "montanha-perto-do-corpo-de-agua-cs0sK0gzqCU",
    },
    created_at: "2017-08-11T20:10:30Z",
    updated_at: "2024-10-01T00:22:23Z",
    promoted_at: "2017-08-12T12:31:42Z",
    width: 6853,
    height: 4574,
    color: "#262626",
    blur_hash: "L46u6LE100-pk[j=Rht74nt7%LR*",
    description:
      "Taken 1 year ago by @hofer teresa, daughter from my colleague in the Zillertaler Alps, Nothern Italy! I always loved this picture, i think now is the right moment to publish it!",
    alt_description: "mountain near body of water",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1502481851512-e9e2529bfbf9?ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1502481851512-e9e2529bfbf9?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1502481851512-e9e2529bfbf9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1502481851512-e9e2529bfbf9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1502481851512-e9e2529bfbf9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1502481851512-e9e2529bfbf9",
    },
    links: {
      self: "https://api.unsplash.com/photos/mountain-near-body-of-water-cs0sK0gzqCU",
      html: "https://unsplash.com/photos/mountain-near-body-of-water-cs0sK0gzqCU",
      download:
        "https://unsplash.com/photos/cs0sK0gzqCU/download?ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8",
      download_location:
        "https://api.unsplash.com/photos/cs0sK0gzqCU/download?ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8",
    },
    likes: 2823,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      nature: {
        status: "approved",
        approved_on: "2024-03-26T19:27:07Z",
      },
    },
    asset_type: "photo",
    user: {
      id: "XZDJrfKzdWY",
      updated_at: "2024-10-02T16:48:54Z",
      username: "eberhardgross",
      name: "eberhard 🖐 grossgasteiger",
      first_name: "eberhard 🖐",
      last_name: "grossgasteiger",
      twitter_username: null,
      portfolio_url: "https://narrateography.art",
      bio: "Photography is so incredibly complex, although seemingly simplistic.",
      location: "South Tyrol, Italy",
      links: {
        self: "https://api.unsplash.com/users/eberhardgross",
        html: "https://unsplash.com/@eberhardgross",
        photos: "https://api.unsplash.com/users/eberhardgross/photos",
        likes: "https://api.unsplash.com/users/eberhardgross/likes",
        portfolio: "https://api.unsplash.com/users/eberhardgross/portfolio",
        following: "https://api.unsplash.com/users/eberhardgross/following",
        followers: "https://api.unsplash.com/users/eberhardgross/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1593541755358-41ff2a4e41efimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1593541755358-41ff2a4e41efimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1593541755358-41ff2a4e41efimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "eberhard_grossgasteiger",
      total_collections: 6,
      total_likes: 4796,
      total_photos: 2038,
      total_promoted_photos: 1815,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: "eberhard_grossgasteiger",
        portfolio_url: "https://narrateography.art",
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: "Canon",
      model: "Canon EOS 70D",
      name: "Canon, EOS 70D",
      exposure_time: "20",
      aperture: "2.8",
      focal_length: "14.0",
      iso: 800,
    },
    location: {
      name: "Zillertal Alps, Italy",
      city: null,
      country: "Italy",
      position: {
        latitude: 47.022447,
        longitude: 11.9016289,
      },
    },
    views: 45682729,
    downloads: 1295630,
  },
  {
    id: "kN6jt0hu51s",
    slug: "constellation-view-at-night-time-kN6jt0hu51s",
    alternative_slugs: {
      en: "constellation-view-at-night-time-kN6jt0hu51s",
      es: "vista-de-la-constelacion-por-la-noche-kN6jt0hu51s",
      ja: "夜の星座ビュー-kN6jt0hu51s",
      fr: "vue-de-la-constellation-la-nuit-kN6jt0hu51s",
      it: "vista-della-costellazione-di-notte-kN6jt0hu51s",
      ko: "야간의-별자리-보기-kN6jt0hu51s",
      de: "sternbildansicht-bei-nacht-kN6jt0hu51s",
      pt: "vista-da-constelacao-durante-a-noite-kN6jt0hu51s",
    },
    created_at: "2018-12-02T02:53:00Z",
    updated_at: "2024-09-07T23:43:06Z",
    promoted_at: "2018-12-02T10:25:57Z",
    width: 7952,
    height: 5304,
    color: "#262626",
    blur_hash: "L26H$G009F?H00^+t79ZIVoMjXt7",
    description: null,
    alt_description: "constellation view at night time",
    breadcrumbs: [
      {
        slug: "images",
        title: "1,000,000+ Free Images",
        index: 0,
        type: "landing_page",
      },
      {
        slug: "nature",
        title: "Nature Images",
        index: 1,
        type: "landing_page",
      },
    ],
    urls: {
      raw: "https://images.unsplash.com/photo-1543719175-29cb1cfe3307?ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1543719175-29cb1cfe3307?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1543719175-29cb1cfe3307?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1543719175-29cb1cfe3307?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1543719175-29cb1cfe3307?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1543719175-29cb1cfe3307",
    },
    links: {
      self: "https://api.unsplash.com/photos/constellation-view-at-night-time-kN6jt0hu51s",
      html: "https://unsplash.com/photos/constellation-view-at-night-time-kN6jt0hu51s",
      download:
        "https://unsplash.com/photos/kN6jt0hu51s/download?ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8",
      download_location:
        "https://api.unsplash.com/photos/kN6jt0hu51s/download?ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8",
    },
    likes: 112,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      nature: {
        status: "approved",
        approved_on: "2020-04-06T14:20:12Z",
      },
    },
    asset_type: "photo",
    user: {
      id: "194BEP8tZbw",
      updated_at: "2024-09-30T14:19:02Z",
      username: "rheuer22",
      name: "Ryan Heuer",
      first_name: "Ryan",
      last_name: "Heuer",
      twitter_username: "rheuer22",
      portfolio_url: "http://www.ryanheuer.com",
      bio: "Tech geek, astrophotographer, travel enthusiast.",
      location: "Illinois",
      links: {
        self: "https://api.unsplash.com/users/rheuer22",
        html: "https://unsplash.com/@rheuer22",
        photos: "https://api.unsplash.com/users/rheuer22/photos",
        likes: "https://api.unsplash.com/users/rheuer22/likes",
        portfolio: "https://api.unsplash.com/users/rheuer22/portfolio",
        following: "https://api.unsplash.com/users/rheuer22/following",
        followers: "https://api.unsplash.com/users/rheuer22/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1664120346924-383017016103?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1664120346924-383017016103?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1664120346924-383017016103?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "heuer.photography",
      total_collections: 0,
      total_likes: 3,
      total_photos: 38,
      total_promoted_photos: 7,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: "heuer.photography",
        portfolio_url: "http://www.ryanheuer.com",
        twitter_username: "rheuer22",
        paypal_email: null,
      },
    },
    exif: {
      make: "SONY",
      model: "ILCE-7RM3",
      name: "SONY, ILCE-7RM3",
      exposure_time: "20",
      aperture: "2.8",
      focal_length: "24.0",
      iso: 1600,
    },
    location: {
      name: null,
      city: null,
      country: null,
      position: {
        latitude: null,
        longitude: null,
      },
    },
    views: 7171683,
    downloads: 7239,
  },
  {
    id: "5jSRM-M1z2Y",
    slug: "green-leafed-trees-under-night-sky-5jSRM-M1z2Y",
    alternative_slugs: {
      en: "green-leafed-trees-under-night-sky-5jSRM-M1z2Y",
      es: "arboles-de-hojas-verdes-bajo-el-cielo-nocturno-5jSRM-M1z2Y",
      ja: "夜空の下の緑の葉の木々-5jSRM-M1z2Y",
      fr: "arbres-a-feuilles-vertes-sous-le-ciel-nocturne-5jSRM-M1z2Y",
      it: "alberi-a-foglia-verde-sotto-il-cielo-notturno-5jSRM-M1z2Y",
      ko: "밤하늘-아래-푸른-잎이-무성한-나무-5jSRM-M1z2Y",
      de: "grun-belaubte-baume-unter-dem-nachthimmel-5jSRM-M1z2Y",
      pt: "arvores-de-folhas-verdes-sob-o-ceu-noturno-5jSRM-M1z2Y",
    },
    created_at: "2018-09-21T21:02:22Z",
    updated_at: "2024-10-02T12:10:56Z",
    promoted_at: "2018-09-22T12:40:12Z",
    width: 3000,
    height: 2000,
    color: "#264040",
    blur_hash: "L75rV*MxoIbbp0ofjsf68^x]WCjE",
    description:
      "Milky way from my terrace. Better this time. Next time even more better-rer",
    alt_description: "green leafed trees under night sky",
    breadcrumbs: [
      {
        slug: "images",
        title: "1,000,000+ Free Images",
        index: 0,
        type: "landing_page",
      },
      {
        slug: "nature",
        title: "Nature Images",
        index: 1,
        type: "landing_page",
      },
      {
        slug: "fall",
        title: "Fall Images & Pictures",
        index: 2,
        type: "landing_page",
      },
    ],
    urls: {
      raw: "https://images.unsplash.com/photo-1537563626051-5a6859a8d099?ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1537563626051-5a6859a8d099?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1537563626051-5a6859a8d099?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1537563626051-5a6859a8d099?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1537563626051-5a6859a8d099?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1537563626051-5a6859a8d099",
    },
    links: {
      self: "https://api.unsplash.com/photos/green-leafed-trees-under-night-sky-5jSRM-M1z2Y",
      html: "https://unsplash.com/photos/green-leafed-trees-under-night-sky-5jSRM-M1z2Y",
      download:
        "https://unsplash.com/photos/5jSRM-M1z2Y/download?ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8",
      download_location:
        "https://api.unsplash.com/photos/5jSRM-M1z2Y/download?ixid=M3w2NjA0MjZ8MHwxfHJhbmRvbXx8fHx8fHx8fDE3Mjc4OTA3NTZ8",
    },
    likes: 232,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      nature: {
        status: "approved",
        approved_on: "2021-02-26T11:13:36Z",
      },
    },
    asset_type: "photo",
    user: {
      id: "hBOiTZnIZ64",
      updated_at: "2024-09-12T19:58:56Z",
      username: "pueblovista",
      name: "Paul Pastourmatzis",
      first_name: "Paul",
      last_name: "Pastourmatzis",
      twitter_username: "pueblovista",
      portfolio_url: "https://pueblo-vista.com",
      bio: "Visual Designer by day and content creator (photography, film and music) by night.",
      location: "Thessaloniki, Greece",
      links: {
        self: "https://api.unsplash.com/users/pueblovista",
        html: "https://unsplash.com/@pueblovista",
        photos: "https://api.unsplash.com/users/pueblovista/photos",
        likes: "https://api.unsplash.com/users/pueblovista/likes",
        portfolio: "https://api.unsplash.com/users/pueblovista/portfolio",
        following: "https://api.unsplash.com/users/pueblovista/following",
        followers: "https://api.unsplash.com/users/pueblovista/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1726171134133-968f2196af32image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1726171134133-968f2196af32image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1726171134133-968f2196af32image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "pueblo_vista",
      total_collections: 19,
      total_likes: 1067,
      total_photos: 369,
      total_promoted_photos: 190,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: "pueblo_vista",
        portfolio_url: "https://pueblo-vista.com",
        twitter_username: "pueblovista",
        paypal_email: null,
      },
    },
    exif: {
      make: null,
      model: null,
      name: null,
      exposure_time: null,
      aperture: null,
      focal_length: null,
      iso: null,
    },
    location: {
      name: "Innsbruck, Austria",
      city: "Innsbruck",
      country: "Austria",
      position: {
        latitude: 47.2692124,
        longitude: 11.4041024000001,
      },
    },
    views: 7799663,
    downloads: 8146,
  },
];
